apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: pyspark-pi
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: hyunsoolee0506/sparkoperator:0.1
  imagePullPolicy: Always
  mainApplicationFile: local:///mnt/python-db.py
  sparkVersion: "3.5.0"
  timeToLiveSeconds: 120
  volumes:
    - name: sparkjob-vol
      persistentVolumeClaim:
        claimName: sparkjob-pvc
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.5.0
    serviceAccount: spark-spark-operator
    volumeMounts:
      - name: sparkjob-vol
        mountPath: /mnt
    envFrom:
      - secretRef:
          name: ncp-api-key
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.5.0
    serviceAccount: spark-spark-operator
    volumeMounts:
      - name: sparkjob-vol
        mountPath: /mnt
    envFrom:
      - secretRef:
          name: ncp-api-key
