apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: ScheduledSparkApplication
metadata:
  name: pyspark-job-schedule
spec:
  schedule: "@every 1m"

  concurrencyPolicy: Allow
  template:
    type: Python
    pythonVersion: "3"
    mode: cluster
    image: hyunsoolee0506/spark:3.5.0
    imagePullPolicy: Always
    mainApplicationFile: local:///workspace/pyspark/nos-read-write.py
    sparkVersion: "3.5.0"
    timeToLiveSeconds: 120
    driver:
      cores: 1
      coreLimit: "1200m"
      memory: "512m"
      labels:
        version: 3.5.0
      serviceAccount: spark-spark-operator
      envFrom:
        - secretRef:
            name: ncp-secret-key
    executor:
      cores: 1
      instances: 1
      memory: "512m"
      labels:
        version: 3.5.0
      envFrom:
        - secretRef:
            name: ncp-secret-key
