apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: pyspark-job-ncp
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: hyunsoolee0506/spark:3.5.0
  imagePullPolicy: Always
  mainApplicationFile: local:///workspace/pyspark/nos-read-write.py
  sparkVersion: "3.5.0"
  timeToLiveSeconds: 120
  dynamicAllocation:
    enabled: true
    initialExecutors: 2
    minExecutors: 2
    maxExecutors: 10
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.5.0
    serviceAccount: spark-spark-operator
    env:
      - name: NCP_ACCESS_KEY_ID
        value:
      - name: NCP_SECRET_ACCESS_KEY
        value:
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.5.0
    env:
      - name: NCP_ACCESS_KEY_ID
        value:
      - name: NCP_SECRET_ACCESS_KEY
        value:
